const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,disabled:false,innerHTML:'',hidden:false,options:[],querySelectorAll:()=>[],querySelector:()=>null});return nodes.get(id);};
let closed=0,requests=[],focused=0,scrolled=0,modal=false;
const card={classList:{add(){},remove(){}},focus(){focused++;},scrollIntoView(){scrolled++;}};
get('games').querySelector=()=>card;
const context=vm.createContext({console,document:{getElementById:get,createElement:()=>({}),body:{append(){}},querySelector:()=>modal?{}:null,addEventListener(){}},render(){},persistView(){},t:x=>x,e:x=>String(x).replace(/[<>&"]/g,'_'),displayValue:x=>x,toast(){},crypto:{randomUUID:()=> 'new'},Option:function(text,value){this.value=value;},api:async(path,body)=>{requests.push(body);return body;},filteredGames:()=>[{id:1,title:'Ratchet & Clank'},{id:2,title:'Portal'}]});
vm.runInContext(fs.readFileSync('static/app.js','utf8').split('let statuses =')[0],context);
context.dialog={getBoundingClientRect:()=>({left:10,right:100,top:10,bottom:100})};context.close=()=>closed++;
vm.runInContext('wireDialogBackdrop(dialog,close)',context);
const ev=(x,y,target=context.dialog,button=0)=>({clientX:x,clientY:y,target,button});
context.dialog.onpointerdown(ev(40,40,{}));context.dialog.onclick(ev(0,40));assert.equal(closed,0,'selection drag must not dismiss');
context.dialog.onpointerdown(ev(0,40));context.dialog.onclick(ev(0,40));assert.equal(closed,1,'genuine backdrop click dismisses');
context.dialog.onpointerdown(ev(0,40));context.dialog.onclick(ev(40,40));assert.equal(closed,1);
context.dialog.onpointerdown(ev(0,40));context.dialog.onpointercancel();context.dialog.onclick(ev(0,40));assert.equal(closed,1);
context.dialog.onpointerdown(ev(0,40,context.dialog,2));context.dialog.onclick(ev(0,40,context.dialog,2));assert.equal(closed,1);
vm.runInContext("let preferences={saved_collections:[]},statusFilter='',direction=1,viewMode='cards',activeCategoryView='all';",context);
vm.runInContext(fs.readFileSync('static/library-navigation.js','utf8'),context);
get('librarySearch').value='Rat';get('platformFilter').value='PC';get('unknownRelease').checked=true;get('sortField').value='title';
assert.equal(vm.runInContext('activeLibraryFilters().length',context),3);
const state=vm.runInContext('captureCollectionState()',context);assert.equal(state.librarySearch,'Rat');
vm.runInContext("clearLibraryFilter('librarySearch')",context);assert.equal(get('librarySearch').value,'');assert.equal(get('platformFilter').value,'PC');
context.snapshot=state;vm.runInContext('applyCollectionState(snapshot)',context);assert.equal(get('librarySearch').value,'Rat');
const event=key=>({key,target:{closest:()=>null},preventDefault(){this.prevented=true;}});
for(const key of ['R','a','t'])context.libraryTypeJump(event(key));assert.equal(scrolled,3);assert.equal(focused,3);
context.libraryTypeJump({...event('P'),target:{closest:()=>({})}});assert.equal(scrolled,3);
modal=true;context.libraryTypeJump(event('P'));assert.equal(scrolled,3);modal=false;
context.libraryTypeJump(event('P'));assert.equal(scrolled,4);
(async()=>{
 context.items=[{id:'one',name:'Rat games',state}];await vm.runInContext("storeCollections(items,'one')",context);
 assert.equal(requests.length,1);assert.equal(vm.runInContext('preferences.saved_collections[0].name',context),'Rat games');
 get('savedCollection').value='one';get('savedCollection').onchange();assert.equal(get('librarySearch').value,'Rat');
 get('librarySearch').value='Portal';get('updateCollection').onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(requests.at(-1).saved_collections[0].state.librarySearch,'Portal');
 get('deleteCollection').onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(requests.at(-1).saved_collections.length,0);
 assert.equal(get('librarySearch').value,'Portal','deleting collection must not remove games or change current filters');
 console.log('Backdrop drag/cancel/right click; filter chips; collection save/apply/update/delete; typing navigation and input/modal guards: OK');
})().catch(error=>{console.error(error);process.exitCode=1;});
